# playbook.yml
---
- name: Deploy Nginx configuration
  hosts: web_servers
  become: yes
  tasks:
    - name: Copy the Nginx configuration files from template
      template:
        src: templates/nginx.conf.j2
        dest: /etc/nginx/nginx.conf
      notify: Restart Nginx 

  handlers:
    - name: Restart Nginx
      service:
          name: nginx
          state: restarted
